### ISSUE TITLE
Template string instead of function call

### ISSUE THREAD

**Issue by linonetwo** [suchipi/jsh#1]
It will save some typing, I mean keyboard typing.

**Comment by suchipi** [comment]
For `exec` and `$`? Yeah, that's a good idea

**Comment by suchipi** [comment]
I'd want it to support both the existing function call as well as a template string, though

**Comment by lily-controlzee** [comment]
Actually, I changed my mind; I'm not gonna do this, because maintaining two different types of calls makes things complicated, and the `(` and `)` aren't that big of a deal.

**Comment by suchipi** [comment]
Actually, I changed my mind; I'm not gonna do this, because maintaining two different types of calls makes things complicated, and the `(` and `)` aren't that big of a deal.
